version: '3.9'
services:
    database:
        image: postgres:14
        restart: always
        container_name: tinitiate_postgres
        volumes: 
          - ./db-data:/var/lib/postgresql/data
          # - ./csv/loan_rules.csv:/var/lib/postgresql/data/pgdata/
          - ./scripts/init.sql:/docker-entrypoint-initdb.d/10-init.sql
          - ./scripts/init2.sql:/docker-entrypoint-initdb.d/20-init2.sql
          - ./scripts/init3.sql:/docker-entrypoint-initdb.d/30-init3.sql
          

        ports:
          - '5432:5432'
        environment:
          POSTGRES_USER: tinitiate
          POSTGRES_PASSWORD: tinitiate
          POSTGRES_DB: tinitiate
        logging:
          options:
            max-size: 10m
            max-file: "3"
networks:
  default:
    name: tinitiate
    external: true